# Generated by Django 5.0.7 on 2024-07-31 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('team_image', models.ImageField(upload_to='uploads/teams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
